name: Sync Playlist

on:
  push:
    branches:
    - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: npm ci && npm run sync
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    - name: push
      uses: actions-x/commit@v2
      with:
        name: Spotify Git Bot
        email: post+spotifygit@juergensen.me
        message: Update Playlists
