name: Sync Playlist

on:
  push:
    branches:
    - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

    
jobs:
  build:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: npm ci && npm run sync
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: main
        commit-message: 'Update Playlists'
        name: Spotify Git
        email: post+spofitygit@juergensen.me 
